# Generated by Django 4.2.7 on 2023-11-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platos',
            new_name='Plato',
        ),
    ]
