# Generated by Django 4.2.5 on 2023-11-27 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_delete_usuarios_rename_id_pedido_pedidos_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='nom_plato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.plato'),
            preserve_default=False,
        ),
    ]
